### ISSUE TITLE
Have one conda environment instead of many

### ISSUE THREAD

**Issue by absolute-afloat** [highRES-model/highRES-Europe-WF#1]
@James-Price has already made progress on this.

**Comment by OskarVagero** [comment]
I would have thought that PR #43  and commit 17f8300c7a320a2d5e18d014689fabfdd63422c9 would have closed this issue, but when I looked at the main branch, it looks like the rules, for example rule build_hydro_capfac, uses the old environment files:

rule build_hydro_capfac:
...
      conda:
		"envs/build_hydro_capfac.yml"

Does this mean that the model will not run the way the workflow is set up?

**Comment by OskarVagero** [comment]
This issue is resolved through PR #43. One should no longer run in a snakemake minimal environment, but rather from highres_environment.yaml, without specifying the --use-conda argument in snakemake. 

Closing this issue.
