### ISSUE TITLE
Setup ReadTheDocs

### ISSUE THREAD

**Issue by absolute-afloat** [highRES-model/highRES-Europe-WF#11]
[OskarVagero](https://github.com/OskarVagero) Sep 20, 2023

As discussed with James at the meeting (19 September 2023), we would look into improving the README and documenting it through a [Read the Docs](https://about.readthedocs.com/?ref=readthedocs.com).

**Comment by OskarVagero** [comment]
Last thing to do in the issue is to link to the documentation in the README (to make it public and accessible). The initial skeleton is setup. 

Further improvements in a separate issue
