### ISSUE TITLE
Bug in highRES_build_hydro.py.ipynb

### ISSUE THREAD

**Issue by JavedMS** [highRES-model/highRES-Europe-WF#13]
Hi,

I went through highRES_build_hydro.py.ipynb file and think that the rorcapfac calculation is done directly from the cut. Runoff inflows. It needs to be multiplied by the percent run-of-river installed rated capacity as it is done in the case of hydrores inflows. I am attaching the screenshot of the relevant code lines where changes need to be made.  

![rorcode_lines](https://github.com/highRES-model/highRES-Europe-WF/assets/153289444/b64641ad-40a9-46e2-acda-795ed2c76981)

**Comment by OskarVagero** [comment]
Thank you for pointing out the bug! 

After testing, I think I've worked out the solution. 

The following addition should do the trick:
`ror_capfac = (
    inflow.to_pandas()
    .T
    .stack()
    .to_frame()
    .rename(columns={0:'value'})
    .mul((
        df_cap_shares
        .reset_index()
        .rename(columns={'MapCode' : 'countries', 'share_ror' : 'value'})
        .set_index('countries')
        .loc[:,['value']])
        )
    .div(df_installed_ror, axis="index", level="countries")
   .loc[:,'value']
)`

It requires some converting from series -> dataframe -> series, but does the trick. Will create a pull request to update the notebook accordingly. 

Below is an examplary graphical illustration of the inflow:
![Screenshot from 2024-02-07 15-10-42](https://github.com/highRES-model/highRES-Europe-WF/assets/99019018/466b7153-5ff2-45e4-afe4-357fddad844b)

**Comment by OskarVagero** [comment]
This issue has been resolved by pull request #15
