### ISSUE TITLE
nuts_to_ssb in highRES-build_weather notebook

### ISSUE THREAD

**Issue by tobiasvh15** [highRES-model/highRES-Europe-WF#31]
`nuts_to_ssb` should probably not be part of the European version?

https://github.com/highRES-model/highRES-Europe-WF/blob/2e4d087a2fbea14d8b4e18d8d908b743cd668709/workflow/notebooks/highRES-build_weather.py.ipynb#L922

**Comment by OskarVagero** [comment]
This issue has been resolved with the changes brought in through pull request #43, where rule build_weather was disaggregated.
